name: CI

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/checkout@v2
        with:
          toolchain: stable

      - name: List contents before directory change
        run: ls -al

      - name: Change to caesar-cipher-cli directory
        run: cd caesar-cipher-cli

      - name: List contents after directory change
        run: ls -al


      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Deploy
        run: make deploy
