name: CI

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/checkout@v3

      - name: Build and Test
        with:
          repository: nogibjj/Haochong-week7-rust-data-engineering
          path: caesar-cipher-cli
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Deploy
        run: make deploy
