name: CI

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: actions/checkout@v3
        with:
          repository: nogibjj/Haochong-week7-rust
          path: caesar-cipher-cli

      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Deploy
        run: make deploy
